---
- name: Enable Docker APT Repository
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/debian jessie stable
    state: present

- name: Add Docker APT Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 0EBFCD88
    state: present

# Makes sure that the repo cache is fresh
- name: Package Maintence
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
    autoremove: yes

- name: Install Packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - docker-ce

- name: Install raspi-config
  apt:
    name: raspi-config
    state: latest

- name: Get disk info
  shell: df -h
  changed_when: False
  register: disk_info

- name: Expand File System
  shell: raspi-config --expand-rootfs
  become: true
  when: "disk_info.stdout.find('/dev/root        15G') == -1"

# Setup the Docker Swarm Cluster
- include: swarm_cluster.yml
